#!/usr/bin/env bash
# This script transfers a file from the client to a server using scp

# Display usage message if less than 4 parameters are passed
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assigning parameters to variables
file_path="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

# Transfer the file to the user's home directory on the server
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username@$server_ip":~/ 

# Check if scp command was successful
if [ $? -eq 0 ]; then
    echo "File transferred successfully to $username@$server_ip:~/"
else
    echo "File transfer failed"
fi

