#!/usr/bin/env bash
# This script configures Nginx to add a custom HTTP response header
# The custom header contains the hostname of the server Nginx is running on

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Set up custom Nginx configuration
echo 'server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files $uri $uri/ =404;
    }

    add_header X-Served-By $HOSTNAME;
}' | sudo tee /etc/nginx/sites-available/default > /dev/null

# Reload Nginx to apply changes
sudo systemctl reload nginx

