#!/usr/bin/env bash
# This script answers the types of network questions.

# Question 1: What type of network a computer in local is connected to?
# 1. Internet
# 2. WAN
# 3. LAN

# Answer 1: 3
echo "3"

# Question 2: What type of network could connect an office in one building to another office in a building a few streets away?
# 1. Internet
# 2. WAN
# 3. LAN

# Answer 2: 2
echo "2"

# Question 3: What network do you use when you browse www.google.com from your smartphone (not connected to the Wifi)?
# 1. Internet
# 2. WAN
# 3. LAN

# Answer 3: 1
echo "1"
