#!/usr/bin/env bash
# This script provides answers to the UDP and TCP questions.

# Question 1: Which statement is correct for the TCP box?
# 1. It is a protocol that is transferring data in a slow way but surely
# 2. It is a protocol that is transferring data in a fast way and might lose data along in the process

# Answer 1: 1
echo "1"

# Question 2: Which statement is correct for the UDP box?
# 1. It is a protocol that is transferring data in a slow way but surely
# 2. It is a protocol that is transferring data in a fast way and might lose data along in the process

# Answer 2: 2
echo "2"

# Question 3: Which statement is correct for the TCP worker?
# 1. Have you received boxes x, y, z?
# 2. May I increase the rate at which I am sending you boxes?

# Answer 3: 1
echo "1"
